services:
  profile-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: ${PROFILE_DB_PASSWORD}
      POSTGRES_USER: ${PROFILE_DB_USER}
      POSTGRES_DB: ${PROFILE_DB_NAME}
    ports:
      - "5460:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PROFILE_DB_USER} -d ${PROFILE_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - haxer-net
    volumes:
      - profile-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  profile-service:
    build:
      context: .
      dockerfile: profile_service/Dockerfile
    environment:
      HOST: ${PROFILE_DB_HOST}
      USER: ${PROFILE_DB_USER}
      PASSWORD: ${PROFILE_DB_PASSWORD}
      SSLMODE: ${PROFILE_DB_SSLMODE}
      PROFILE_DBNAME: ${PROFILE_DB_NAME}
      PROFILE_PORT: ${PROFILE_DB_PORT}

      JWT_SECRET: ${JWT_SECRET}

      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_TOPIC: ${PROFILE_EVENTS_TOPIC}
      KAFKA_CLIENT_ID: ${PROFILE_KAFKA_CLIENT_ID}
      KAFKA_BATCH_SIZE: ${KAFKA_BATCH_SIZE}
      KAFKA_BATCH_TIMEOUT: ${KAFKA_BATCH_TIMEOUT}
      KAFKA_RETRY_MAX: ${KAFKA_RETRY_MAX}
      KAFKA_RETRY_BACKOFF: ${KAFKA_RETRY_BACKOFF}
      KAFKA_REQUIRED_ACKS: ${KAFKA_REQUIRED_ACKS}
      KAFKA_COMPRESSION: ${KAFKA_COMPRESSION}

      PROFILE_GRPC_AUTH_PORT: ${PROFILE_GRPC_AUTH_PORT}
      PROFILE_GRPC_DIRECTORY_PORT: ${PROFILE_GRPC_DIRECTORY_PORT}
      CHAT_PRESENCE_GRPC_ADDR: ${CHAT_PRESENCE_GRPC_ADDR}
      PROFILE_HTTP_PORT: "8083"
    ports:
      - "8080:8083"
      - "${PROFILE_GRPC_AUTH_PORT}:${PROFILE_GRPC_AUTH_PORT}"
      - "${PROFILE_GRPC_DIRECTORY_PORT}:${PROFILE_GRPC_DIRECTORY_PORT}"
    depends_on:
      profile-db:
        condition: service_healthy
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started
      kafka-3:
        condition: service_started
    networks:
      - haxer-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - haxer-net
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  chat-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_USER: ${CHAT_DB_USER}
      POSTGRES_DB: ${CHAT_DB_NAME}
    ports:
      - "5461:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CHAT_DB_USER} -d ${CHAT_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - haxer-net
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  chat-service:
    build:
      context: .
      dockerfile: chat_service/Dockerfile
    environment:
      HOST: ${CHAT_DB_HOST}
      USER: ${CHAT_DB_USER}
      PASSWORD: ${CHAT_DB_PASSWORD}
      SSLMODE: ${CHAT_DB_SSLMODE}
      ROOM_DBNAME: ${CHAT_DB_NAME}
      ROOM_DBPORT: ${CHAT_DB_PORT}

      JWT_SECRET: ${JWT_SECRET}
      CHAT_HTTP_PORT: "8084"

      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_DB: ${REDIS_DB}
      IDLE_THRESHOLD: ${IDLE_THRESHOLD}

      PROFILE_SERVICE_AUTH_ADDR: ${PROFILE_AUTH_GRPC_ADDR}
      PROFILE_SERVICE_DIRECTORY_ADDR: ${PROFILE_DIRECTORY_GRPC_ADDR}
      CHAT_GRPC_PRESENCE_PORT: ${CHAT_GRPC_PRESENCE_PORT}
    ports:
      - "8081:8084"
      - "${CHAT_GRPC_PRESENCE_PORT}:${CHAT_GRPC_PRESENCE_PORT}"
    depends_on:
      chat-db:
        condition: service_healthy
      profile-service:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - haxer-net
    restart: unless-stopped

  notification-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
    ports:
      - "5462:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NOTIFICATION_DB_USER} -d ${NOTIFICATION_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - haxer-net
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    environment:
      HOST: ${NOTIFICATION_DB_HOST}
      USER: ${NOTIFICATION_DB_USER}
      PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      SSLMODE: ${NOTIFICATION_DB_SSLMODE}
      NOTIFICATION_DBNAME: ${NOTIFICATION_DB_NAME}
      NOTIFICATION_DBPORT: ${NOTIFICATION_DB_PORT}

      JWT_SECRET: ${JWT_SECRET}
      NOTIFICATION_HTTP_PORT: "8086"

      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_TOPIC: ${PROFILE_EVENTS_TOPIC}
      KAFKA_CLIENT_ID: ${NOTIFICATION_KAFKA_CLIENT_ID}
      KAFKA_CONSUMER_GROUP: ${NOTIFICATION_CONSUMER_GROUP}
      KAFKA_RETRY_MAX: ${KAFKA_RETRY_MAX}
      KAFKA_RETRY_BACKOFF: ${KAFKA_RETRY_BACKOFF}

      PROFILE_SERVICE_AUTH_ADDR: ${PROFILE_AUTH_GRPC_ADDR}
      PROFILE_SERVICE_DIRECTORY_ADDR: ${PROFILE_DIRECTORY_GRPC_ADDR}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
    ports:
      - "8086:8086"
    depends_on:
      notification-db:
        condition: service_healthy
      profile-service:
        condition: service_started
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    networks:
      - haxer-net
    restart: unless-stopped

  kafka-1:
    image: apache/kafka:4.2.0
    container_name: kafka-1
    networks:
      - haxer-net
    restart: unless-stopped
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s


  kafka-2:
    image: apache/kafka:4.2.0
    container_name: kafka-2
    networks:
      - haxer-net
    restart: unless-stopped
    ports:
      - "9095:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9095'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s

  kafka-3:
    image: apache/kafka:4.2.0
    container_name: kafka-3
    networks:
      - haxer-net
    restart: unless-stopped
    ports:
      - "9096:9094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:9092,EXTERNAL://localhost:9096'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    networks:
      - haxer-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

networks:
  haxer-net:
    driver: bridge

volumes:
  profile-db-data:
  chat-db-data:
  notification-db-data:
  redis-data: