// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: profile/authz.proto

package profile

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanSendDirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanSendDirectRequest) Reset() {
	*x = CanSendDirectRequest{}
	mi := &file_profile_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanSendDirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanSendDirectRequest) ProtoMessage() {}

func (x *CanSendDirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanSendDirectRequest.ProtoReflect.Descriptor instead.
func (*CanSendDirectRequest) Descriptor() ([]byte, []int) {
	return file_profile_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CanSendDirectRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *CanSendDirectRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type CanSendDirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanSendDirectResponse) Reset() {
	*x = CanSendDirectResponse{}
	mi := &file_profile_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanSendDirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanSendDirectResponse) ProtoMessage() {}

func (x *CanSendDirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanSendDirectResponse.ProtoReflect.Descriptor instead.
func (*CanSendDirectResponse) Descriptor() ([]byte, []int) {
	return file_profile_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CanSendDirectResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanSendDirectResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CanJoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanJoinRoomRequest) Reset() {
	*x = CanJoinRoomRequest{}
	mi := &file_profile_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanJoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanJoinRoomRequest) ProtoMessage() {}

func (x *CanJoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanJoinRoomRequest.ProtoReflect.Descriptor instead.
func (*CanJoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_profile_authz_proto_rawDescGZIP(), []int{2}
}

func (x *CanJoinRoomRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CanJoinRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type CanJoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanJoinRoomResponse) Reset() {
	*x = CanJoinRoomResponse{}
	mi := &file_profile_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanJoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanJoinRoomResponse) ProtoMessage() {}

func (x *CanJoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanJoinRoomResponse.ProtoReflect.Descriptor instead.
func (*CanJoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_profile_authz_proto_rawDescGZIP(), []int{3}
}

func (x *CanJoinRoomResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanJoinRoomResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_profile_authz_proto protoreflect.FileDescriptor

const file_profile_authz_proto_rawDesc = "" +
	"\n" +
	"\x13profile/authz.proto\x12\aprofile\"V\n" +
	"\x14CanSendDirectRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\"I\n" +
	"\x15CanSendDirectResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"F\n" +
	"\x12CanJoinRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\"G\n" +
	"\x13CanJoinRoomResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xb0\x01\n" +
	"\x14AuthorizationService\x12N\n" +
	"\rCanSendDirect\x12\x1d.profile.CanSendDirectRequest\x1a\x1e.profile.CanSendDirectResponse\x12H\n" +
	"\vCanJoinRoom\x12\x1b.profile.CanJoinRoomRequest\x1a\x1c.profile.CanJoinRoomResponseB,Z*profile_service/pkg/grpc_generated/profileb\x06proto3"

var (
	file_profile_authz_proto_rawDescOnce sync.Once
	file_profile_authz_proto_rawDescData []byte
)

func file_profile_authz_proto_rawDescGZIP() []byte {
	file_profile_authz_proto_rawDescOnce.Do(func() {
		file_profile_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_authz_proto_rawDesc), len(file_profile_authz_proto_rawDesc)))
	})
	return file_profile_authz_proto_rawDescData
}

var file_profile_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_profile_authz_proto_goTypes = []any{
	(*CanSendDirectRequest)(nil),  // 0: profile.CanSendDirectRequest
	(*CanSendDirectResponse)(nil), // 1: profile.CanSendDirectResponse
	(*CanJoinRoomRequest)(nil),    // 2: profile.CanJoinRoomRequest
	(*CanJoinRoomResponse)(nil),   // 3: profile.CanJoinRoomResponse
}
var file_profile_authz_proto_depIdxs = []int32{
	0, // 0: profile.AuthorizationService.CanSendDirect:input_type -> profile.CanSendDirectRequest
	2, // 1: profile.AuthorizationService.CanJoinRoom:input_type -> profile.CanJoinRoomRequest
	1, // 2: profile.AuthorizationService.CanSendDirect:output_type -> profile.CanSendDirectResponse
	3, // 3: profile.AuthorizationService.CanJoinRoom:output_type -> profile.CanJoinRoomResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_authz_proto_init() }
func file_profile_authz_proto_init() {
	if File_profile_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_authz_proto_rawDesc), len(file_profile_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_authz_proto_goTypes,
		DependencyIndexes: file_profile_authz_proto_depIdxs,
		MessageInfos:      file_profile_authz_proto_msgTypes,
	}.Build()
	File_profile_authz_proto = out.File
	file_profile_authz_proto_goTypes = nil
	file_profile_authz_proto_depIdxs = nil
}
