basePath: /api/v1
definitions:
  api_dto.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  api_dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api_dto.LoginResponse:
    properties:
      token:
        type: string
      user_id:
        type: string
    type: object
  api_dto.UpdateUserRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
    type: object
  api_dto.UserViewListResponse:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/api_dto.UserViewResponse'
        type: array
    type: object
  api_dto.UserViewResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  middleware_profile.ErrorResponse:
    properties:
      error:
        example: Invalid request parameters
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: API для управления пользователями
  title: ProfileService API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя и возвращает JWT
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход
          schema:
            $ref: '#/definitions/api_dto.LoginResponse'
        "400":
          description: Неверные данные
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      summary: Вход пользователя
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с указанными данными
      parameters:
      - description: Данные для создания пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ID созданного пользователя
          schema:
            type: integer
        "400":
          description: Неверные данные пользователя
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      summary: Создать нового пользователя
      tags:
      - Auth
  /users:
    get:
      consumes:
      - application/json
      description: Возвращает список пользователей с возможностью фильтрации
      parameters:
      - description: Фильтр по имени
        in: query
        name: name
        type: string
      - description: Фильтр по email
        in: query
        name: email
        type: string
      - description: Лимит записей
        in: query
        name: limit
        required: true
        type: integer
      - description: Смещение
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный запрос
          schema:
            $ref: '#/definitions/api_dto.UserViewListResponse'
        "400":
          description: Неверные параметры фильтрации
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить отфильтрованный список пользователей
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет пользователя по указанному ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Пользователь успешно удален
        "400":
          description: Неверный ID пользователя
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить пользователя
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Возвращает информацию о пользователе по его идентификатору
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный запрос
          schema:
            $ref: '#/definitions/api_dto.UserViewResponse'
        "400":
          description: Неверный ID пользователя
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить пользователя по ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Обновляет информацию о пользователе по его ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: Данные успешно обновлены
        "400":
          description: Неверные данные запроса
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/middleware_profile.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить данные пользователя
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
