// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: chat/presence.proto

package chat

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        int64                  `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnConnectRequest) Reset() {
	*x = OnConnectRequest{}
	mi := &file_chat_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnConnectRequest) ProtoMessage() {}

func (x *OnConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnConnectRequest.ProtoReflect.Descriptor instead.
func (*OnConnectRequest) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{0}
}

func (x *OnConnectRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnConnectRequest) GetConnId() int64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *OnConnectRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type OnDisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId        int64                  `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnDisconnectRequest) Reset() {
	*x = OnDisconnectRequest{}
	mi := &file_chat_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnDisconnectRequest) ProtoMessage() {}

func (x *OnDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnDisconnectRequest.ProtoReflect.Descriptor instead.
func (*OnDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{1}
}

func (x *OnDisconnectRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnDisconnectRequest) GetConnId() int64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type OnHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        int64                  `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnHeartbeatRequest) Reset() {
	*x = OnHeartbeatRequest{}
	mi := &file_chat_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnHeartbeatRequest) ProtoMessage() {}

func (x *OnHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*OnHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{2}
}

func (x *OnHeartbeatRequest) GetConnId() int64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_chat_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{3}
}

func (x *GetPresenceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOnlineFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendsIds    []int64                `protobuf:"varint,2,rep,packed,name=friends_ids,json=friendsIds,proto3" json:"friends_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineFriendsRequest) Reset() {
	*x = GetOnlineFriendsRequest{}
	mi := &file_chat_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineFriendsRequest) ProtoMessage() {}

func (x *GetOnlineFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineFriendsRequest) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnlineFriendsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOnlineFriendsRequest) GetFriendsIds() []int64 {
	if x != nil {
		return x.FriendsIds
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_chat_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{5}
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "online", "idle", "offline"
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_chat_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{6}
}

func (x *GetPresenceResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPresenceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPresenceResponse) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetOnlineFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineFriends []int64                `protobuf:"varint,1,rep,packed,name=online_friends,json=onlineFriends,proto3" json:"online_friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineFriendsResponse) Reset() {
	*x = GetOnlineFriendsResponse{}
	mi := &file_chat_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineFriendsResponse) ProtoMessage() {}

func (x *GetOnlineFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineFriendsResponse) Descriptor() ([]byte, []int) {
	return file_chat_presence_proto_rawDescGZIP(), []int{7}
}

func (x *GetOnlineFriendsResponse) GetOnlineFriends() []int64 {
	if x != nil {
		return x.OnlineFriends
	}
	return nil
}

var File_chat_presence_proto protoreflect.FileDescriptor

const file_chat_presence_proto_rawDesc = "" +
	"\n" +
	"\x13chat/presence.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\x10OnConnectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\x03R\x06connId\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"G\n" +
	"\x13OnDisconnectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\x03R\x06connId\"-\n" +
	"\x12OnHeartbeatRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x03R\x06connId\"-\n" +
	"\x12GetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"S\n" +
	"\x17GetOnlineFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vfriends_ids\x18\x02 \x03(\x03R\n" +
	"friendsIds\"\x0f\n" +
	"\rEmptyResponse\"\x7f\n" +
	"\x13GetPresenceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"A\n" +
	"\x18GetOnlineFriendsResponse\x12%\n" +
	"\x0eonline_friends\x18\x01 \x03(\x03R\ronlineFriends2\xd9\x02\n" +
	"\bPresence\x128\n" +
	"\tOnConnect\x12\x16.chat.OnConnectRequest\x1a\x13.chat.EmptyResponse\x12>\n" +
	"\fOnDisconnect\x12\x19.chat.OnDisconnectRequest\x1a\x13.chat.EmptyResponse\x12<\n" +
	"\vOnHeartbeat\x12\x18.chat.OnHeartbeatRequest\x1a\x13.chat.EmptyResponse\x12B\n" +
	"\vGetPresence\x12\x18.chat.GetPresenceRequest\x1a\x19.chat.GetPresenceResponse\x12Q\n" +
	"\x10GetOnlineFriends\x12\x1d.chat.GetOnlineFriendsRequest\x1a\x1e.chat.GetOnlineFriendsResponseB\bZ\x06./gRPCb\x06proto3"

var (
	file_chat_presence_proto_rawDescOnce sync.Once
	file_chat_presence_proto_rawDescData []byte
)

func file_chat_presence_proto_rawDescGZIP() []byte {
	file_chat_presence_proto_rawDescOnce.Do(func() {
		file_chat_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_presence_proto_rawDesc), len(file_chat_presence_proto_rawDesc)))
	})
	return file_chat_presence_proto_rawDescData
}

var file_chat_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chat_presence_proto_goTypes = []any{
	(*OnConnectRequest)(nil),         // 0: chat.OnConnectRequest
	(*OnDisconnectRequest)(nil),      // 1: chat.OnDisconnectRequest
	(*OnHeartbeatRequest)(nil),       // 2: chat.OnHeartbeatRequest
	(*GetPresenceRequest)(nil),       // 3: chat.GetPresenceRequest
	(*GetOnlineFriendsRequest)(nil),  // 4: chat.GetOnlineFriendsRequest
	(*EmptyResponse)(nil),            // 5: chat.EmptyResponse
	(*GetPresenceResponse)(nil),      // 6: chat.GetPresenceResponse
	(*GetOnlineFriendsResponse)(nil), // 7: chat.GetOnlineFriendsResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_chat_presence_proto_depIdxs = []int32{
	8, // 0: chat.GetPresenceResponse.last_seen:type_name -> google.protobuf.Timestamp
	0, // 1: chat.Presence.OnConnect:input_type -> chat.OnConnectRequest
	1, // 2: chat.Presence.OnDisconnect:input_type -> chat.OnDisconnectRequest
	2, // 3: chat.Presence.OnHeartbeat:input_type -> chat.OnHeartbeatRequest
	3, // 4: chat.Presence.GetPresence:input_type -> chat.GetPresenceRequest
	4, // 5: chat.Presence.GetOnlineFriends:input_type -> chat.GetOnlineFriendsRequest
	5, // 6: chat.Presence.OnConnect:output_type -> chat.EmptyResponse
	5, // 7: chat.Presence.OnDisconnect:output_type -> chat.EmptyResponse
	5, // 8: chat.Presence.OnHeartbeat:output_type -> chat.EmptyResponse
	6, // 9: chat.Presence.GetPresence:output_type -> chat.GetPresenceResponse
	7, // 10: chat.Presence.GetOnlineFriends:output_type -> chat.GetOnlineFriendsResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_presence_proto_init() }
func file_chat_presence_proto_init() {
	if File_chat_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_presence_proto_rawDesc), len(file_chat_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_presence_proto_goTypes,
		DependencyIndexes: file_chat_presence_proto_depIdxs,
		MessageInfos:      file_chat_presence_proto_msgTypes,
	}.Build()
	File_chat_presence_proto = out.File
	file_chat_presence_proto_goTypes = nil
	file_chat_presence_proto_depIdxs = nil
}
