// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: chat/presence.proto

package chat

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Presence_OnConnect_FullMethodName        = "/chat.Presence/OnConnect"
	Presence_OnDisconnect_FullMethodName     = "/chat.Presence/OnDisconnect"
	Presence_OnHeartbeat_FullMethodName      = "/chat.Presence/OnHeartbeat"
	Presence_GetPresence_FullMethodName      = "/chat.Presence/GetPresence"
	Presence_GetOnlineFriends_FullMethodName = "/chat.Presence/GetOnlineFriends"
)

// PresenceClient is the client API for Presence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PresenceClient interface {
	// Подключение пользователя (WS/Open session)
	OnConnect(ctx context.Context, in *OnConnectRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Отключение пользователя
	OnDisconnect(ctx context.Context, in *OnDisconnectRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Heartbeat / продление активности
	OnHeartbeat(ctx context.Context, in *OnHeartbeatRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Получение presence пользователя
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error)
	// Получение списка онлайн друзей
	GetOnlineFriends(ctx context.Context, in *GetOnlineFriendsRequest, opts ...grpc.CallOption) (*GetOnlineFriendsResponse, error)
}

type presenceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceClient(cc grpc.ClientConnInterface) PresenceClient {
	return &presenceClient{cc}
}

func (c *presenceClient) OnConnect(ctx context.Context, in *OnConnectRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Presence_OnConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceClient) OnDisconnect(ctx context.Context, in *OnDisconnectRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Presence_OnDisconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceClient) OnHeartbeat(ctx context.Context, in *OnHeartbeatRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Presence_OnHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresenceResponse)
	err := c.cc.Invoke(ctx, Presence_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceClient) GetOnlineFriends(ctx context.Context, in *GetOnlineFriendsRequest, opts ...grpc.CallOption) (*GetOnlineFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineFriendsResponse)
	err := c.cc.Invoke(ctx, Presence_GetOnlineFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServer is the server API for Presence service.
// All implementations must embed UnimplementedPresenceServer
// for forward compatibility.
type PresenceServer interface {
	// Подключение пользователя (WS/Open session)
	OnConnect(context.Context, *OnConnectRequest) (*EmptyResponse, error)
	// Отключение пользователя
	OnDisconnect(context.Context, *OnDisconnectRequest) (*EmptyResponse, error)
	// Heartbeat / продление активности
	OnHeartbeat(context.Context, *OnHeartbeatRequest) (*EmptyResponse, error)
	// Получение presence пользователя
	GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error)
	// Получение списка онлайн друзей
	GetOnlineFriends(context.Context, *GetOnlineFriendsRequest) (*GetOnlineFriendsResponse, error)
	mustEmbedUnimplementedPresenceServer()
}

// UnimplementedPresenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServer struct{}

func (UnimplementedPresenceServer) OnConnect(context.Context, *OnConnectRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnConnect not implemented")
}
func (UnimplementedPresenceServer) OnDisconnect(context.Context, *OnDisconnectRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnDisconnect not implemented")
}
func (UnimplementedPresenceServer) OnHeartbeat(context.Context, *OnHeartbeatRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnHeartbeat not implemented")
}
func (UnimplementedPresenceServer) GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServer) GetOnlineFriends(context.Context, *GetOnlineFriendsRequest) (*GetOnlineFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlineFriends not implemented")
}
func (UnimplementedPresenceServer) mustEmbedUnimplementedPresenceServer() {}
func (UnimplementedPresenceServer) testEmbeddedByValue()                  {}

// UnsafePresenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServer will
// result in compilation errors.
type UnsafePresenceServer interface {
	mustEmbedUnimplementedPresenceServer()
}

func RegisterPresenceServer(s grpc.ServiceRegistrar, srv PresenceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Presence_ServiceDesc, srv)
}

func _Presence_OnConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).OnConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_OnConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).OnConnect(ctx, req.(*OnConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presence_OnDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnDisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).OnDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_OnDisconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).OnDisconnect(ctx, req.(*OnDisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presence_OnHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).OnHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_OnHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).OnHeartbeat(ctx, req.(*OnHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presence_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presence_GetOnlineFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServer).GetOnlineFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Presence_GetOnlineFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServer).GetOnlineFriends(ctx, req.(*GetOnlineFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Presence_ServiceDesc is the grpc.ServiceDesc for Presence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Presence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Presence",
	HandlerType: (*PresenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnConnect",
			Handler:    _Presence_OnConnect_Handler,
		},
		{
			MethodName: "OnDisconnect",
			Handler:    _Presence_OnDisconnect_Handler,
		},
		{
			MethodName: "OnHeartbeat",
			Handler:    _Presence_OnHeartbeat_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _Presence_GetPresence_Handler,
		},
		{
			MethodName: "GetOnlineFriends",
			Handler:    _Presence_GetOnlineFriends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat/presence.proto",
}
